Repository lomsa-dev/http-mock-adapter, pull requests merged in 2020-11, with the labels that each got.

#6 Add basic variant of DioAdapter and other utilities
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  lib/http_mock_adapter.dart
  lib/src/constants.dart
  lib/src/dio_adapter.dart
  lib/src/dio_adapter_mockito.dart
  lib/src/history.dart
  lib/src/http_interceptor.dart
  lib/src/mock_provider.dart
  lib/src/request_handler.dart
  lib/src/utils.dart
  pubspec.lock
  pubspec.yaml
  test/http_mock_adapter_test.dart
Labels: enhancement, high priority

#9 Reorganize the file and code structure
  lib/http_mock_adapter.dart
  lib/src/adapters/dio_adapter.dart
  lib/src/adapters/dio_adapter_mockito.dart
  lib/src/constants.dart
  lib/src/handlers/mock_handler.dart
  lib/src/handlers/request_handler.dart
  lib/src/history.dart
  lib/src/interceptors/http_interceptor.dart
  lib/src/request_handler.dart
Labels: documentation, enhancement, medium priority

#12 Expose Request and RequestMethods to public
  lib/http_mock_adapter.dart
  lib/src/adapters/dio_adapter.dart
  lib/src/handlers/mock_handler.dart
  lib/src/handlers/request_handler.dart
  lib/src/request.dart
Labels: enhancement, good first issue, high priority

#16 Apply major quality of life updates to the whole project
  README.md
  lib/src/adapters/dio_adapter.dart
  lib/src/handlers/mock_handler.dart
  lib/src/handlers/request_handler.dart
  lib/src/history.dart
  lib/src/request.dart
  lib/src/utils.dart
  pubspec.lock
  pubspec.yaml
  test/http_mock_adapter_test.dart
Labels: documentation, enhancement, high priority

#17 .editorconfig first version
  .editorconfig
Labels: enhancement, good first issue, medium priority

#15 Feature/pub automatic publish
  .github/ISSUE_TEMPLATE/workflows/pub.yml
  pub_login.sh
  pubspec.yaml
Labels: documentation, enhancement, medium priority

#18 add dio mockito get and post tests
  lib/http_mock_adapter.dart
  lib/src/adapters/dio_adapter_mockito.dart
  pubspec.lock
  pubspec.yaml
  test/http_mock_adapter_test.dart
Labels: enhancement, high priority, test

#20 analysis options
  analysis_options.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement, good first issue, medium priority

#23 Add lefthook as Git hooks manager
  lefthook.yaml
Labels: documentation, good first issue, medium priority

#30 Add Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement, good first issue, low priority

#26 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, good first issue, low priority

#28 Add Contributing Guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, low priority

#21 Feature/dio interceptor
  lib/src/adapter_interface.dart
  lib/src/adapters/dio_adapter.dart
  lib/src/exceptions.dart
  lib/src/handlers/request_handler.dart
  lib/src/interceptors/http_interceptor.dart
  pubspec.lock
  pubspec.yaml
  test/http_mock_adapter_test.dart
Labels: documentation, enhancement, high priority, test

#36 Fix linter errors and warnings
  lib/src/adapter_interface.dart
  lib/src/exceptions.dart
  lib/src/handlers/request_handler.dart
  lib/src/interceptors/http_interceptor.dart
  lib/src/request.dart
  lib/src/utils.dart
  test/http_mock_adapter_test.dart
Labels: bug, enhancement, help wanted, high priority

#37 add changelog
  CHANGELOG.md
  pubspec.lock
Labels: documentation, enhancement, good first issue, medium priority

#38 Apply major update to README.md
  README.md
Labels: documentation, enhancement, good first issue, high priority

#22 Add non-sequential responding and improve result of fetching
  example/main.dart
  lib/http_mock_adapter.dart
  lib/src/adapter_interface.dart
  lib/src/adapters/dio_adapter.dart
  lib/src/handlers/request_handler.dart
  lib/src/history.dart
  lib/src/interceptors/dio_interceptor.dart
  lib/src/request.dart
  test/http_mock_adapter_test.dart
Labels: documentation, enhancement, high priority, test

#39 added documented examples
  example/main.dart
Labels: documentation, enhancement, medium priority

#40 Update package to version 0.1.0
  CHANGELOG.md
  README.md
  pubspec.lock
  pubspec.yaml
Labels: enhancement, help wanted, high priority

#48 updated request handler class
  lib/src/handlers/request_handler.dart
Labels: bug, enhancement

#49 improved examples
  example/main.dart
Labels: enhancement

#44 added description, corrected socres bug
  README.md
  lib/src/request.dart
Labels: bug, documentation, enhancement

#45 Imporved adapter interface
  lib/src/adapter_interface.dart
  lib/src/request.dart
Labels: enhancement

#52 Fix linting errors, add AUTHORS metadata, update documentation
  .gitattributes
  AUTHORS
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: documentation, medium priority
