Repository lomsa-dev/http-mock-adapter, pull requests merged in 2021-06, with the labels that each got.

#108 Add ListParam matcher
  lib/src/matchers/list_param.dart
  lib/src/matchers/matchers.dart
  test/matchers/list_param_test.dart
Labels: enhancement, medium priority

#110 Fix mocking non-JSON response data
  .gitignore
  lib/src/handlers/request_handler.dart
  test/handlers/request_handler_test.dart
  test/http_mock_adapter_test.dart
Labels: bug, high priority

#114 Maximize package score and update pub badge link
  CHANGELOG.md
  README.md
  lib/src/adapters/dio_adapter.dart
  pubspec.yaml
Labels: bug, enhancement, high priority

#115 Maximize package score and update pub badge link (#114)
  CHANGELOG.md
  README.md
  lib/src/adapters/dio_adapter.dart
  pubspec.yaml
Labels: high priority
