Repository lomsa-dev/http-mock-adapter, pull requests merged in 2021-04, with the labels that each got.

#90 Update to v0.2.1
  .github/workflows/dart-ci.yml
  CHANGELOG.md
  README.md
  lib/src/constants.dart
  lib/src/handlers/mock_handler.dart
  lib/src/utils.dart
  pubspec.yaml
  test/http_mock_adapter_test.dart
  test/utils_test.dart
Labels: enhancement, high priority

#91 Merge v0.2.1 to main
  .github/workflows/dart-ci.yml
  CHANGELOG.md
  README.md
  lib/src/constants.dart
  lib/src/handlers/mock_handler.dart
  lib/src/utils.dart
  pubspec.yaml
  test/http_mock_adapter_test.dart
  test/utils_test.dart
Labels: high priority

#93 Fix example usage in README.md
  README.md
Labels: documentation
