Repository lomsa-dev/http-mock-adapter, pull requests merged in 2023-08, with the labels that each got.

#150 Update Dio to 5.2.0
  .github/workflows/dart-ci.yml
  example/main.dart
  lib/http_mock_adapter.dart
  lib/src/adapters/dio_adapter.dart
  lib/src/exceptions.dart
  lib/src/handlers/request_handler.dart
  lib/src/interceptors/dio_interceptor.dart
  lib/src/mixins/request_handling.dart
  lib/src/response.dart
  pubspec.yaml
  test/adapters/dio_adapter_test.dart
  test/extensions/matches_request_test.dart
  test/handlers/request_handler_test.dart
  test/mixins/recording_test.dart
  test/mixins/request_handling_test.dart
Labels: enhancement

#157 feature/add-callback-and-async-callback
  lib/src/adapters/dio_adapter.dart
  lib/src/handlers/request_handler.dart
  lib/src/interceptors/dio_interceptor.dart
  lib/src/types.dart
  test/handlers/request_handler_test.dart
Labels: bug, enhancement

#158 feature/add exact body check option for FullHttpRequestMatcher
  lib/src/extensions/matches_request.dart
  lib/src/matchers/http_matcher.dart
  test/extensions/matches_request_test.dart
Labels: enhancement

#159 add a next interceptor handler on DioInterceptor for missing mocks
  lib/src/adapters/dio_adapter.dart
  lib/src/interceptors/dio_interceptor.dart
  lib/src/logger/logger.dart
  lib/src/mixins/recording.dart
  lib/src/types.dart
  pubspec.yaml
  test/adapters/dio_adapter_test.dart
  test/interceptors/dio_interceptor_test.dart
Labels: enhancement

#160 chore/downgrade-collection-to-1.17.1
  lib/src/logger/logger.dart
  pubspec.yaml
Labels: bug

#162 release v0.6.0
  CHANGELOG.md
  README.md
  example/main.dart
  pubspec.yaml
Labels: bug, documentation, enhancement, high priority
